### ISSUE TITLE
The search should navigate on enter

### ISSUE THREAD

**Issue by TomasEkeli** [dolittle/Documentation#30]
When pressing enter in the search field if the term has a hit we should navigate to it.

Observed behaviour:
- go to dolittle.io
- Type in "Event Horizon" (do not click the drop-down)
- press enter
- nothing happens

Expected behaviour:
...
- press enter
- user should navigate to the event horizon url

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1129561957579090)

**Comment by joelhoisko** [comment]
It shows now the searched pages, hopefully that's good enough.
