### ISSUE TITLE
Wrongly adding 'display: block' on ul>li>a in the quickstart guide

### ISSUE THREAD

**Issue by pavsaund** [dolittle/Documentation#33]
page: https://dolittle.io/getting-started/quickstart/

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/102054/55459804-acbb9f80-55f0-11e9-9a12-97b17144f4a8.png)

Shouldn't be breaking the text here.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1129559557267607)

**Comment by Virrum** [comment]
Ah... silly styles. Either it's the dot base theme style or it's some third party plugin style, I guess.
