### ISSUE TITLE
Figure out how to include/import the documentation.yml in framework.yml in the Azure DevOps pipelines

### ISSUE THREAD

**Issue by einari** [dolittle/Documentation#42]
Currently, to build the documentation as part of the framework build, the job from documentation.yml was copy-pasted into framework.yml.

To make documentation.yml re-usable across different types of repositories, and not have to update it many places, it would be better if it could be imported.

See: [✓ Hook up Azure DevOps pipeline / steps into existing .NET Framework pipeline](https://app.asana.com/0/0/1131632607679112/f/)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1115616103797671/1132867072805352)

**Comment by joelhoisko** [comment]
This seems to be fixed with https://github.com/dolittle/Documentation/pull/58 but do take note that a commit to master will not trigger the netlify pipeline, only a merge will. This could be something to work on but lately the pipeline has been working.

Closing for now.
